# Generated by Django 5.2.8 on 2026-07-18 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncidentStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated code like STS-001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                (
                    "color_code",
                    models.CharField(
                        blank=True, help_text="Hex color for UI", max_length=7
                    ),
                ),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a final status? (e.g., Resolved, Closed)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Incident Status",
                "verbose_name_plural": "Incident Statuses",
                "ordering": ["ordering", "name"],
            },
        ),
    ]
