# Generated by Django 5.2.8 on 2026-07-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('current_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Employee Sequences',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, help_text='Highest level of education.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.CharField(blank=True, help_text='Current employer or organization.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, help_text='Facebook username or URL.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram username.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text='Hobbies, interests, or passions.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, help_text='A short introduction or bio.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages spoken (comma‑separated).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, help_text='Country of citizenship.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter/X handle.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp phone number.', max_length=20, null=True),
        ),
    ]
