# Generated by Django 5.2.8 on 2026-08-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_employeesequence_user_education_user_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="browser",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="operating_system",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
