# Generated by Django 5.2.8 on 2026-08-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_usersession_browser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginhistory",
            name="browser",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="device_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="operating_system",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
