# Generated by Django 5.2.8 on 2026-07-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-sent_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra metadata (e.g., incident_id, assignment_id)",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ASSIGNMENT", "Assignment"),
                    ("STATUS_UPDATE", "Status Update"),
                    ("ESCALATION", "Escalation"),
                    ("REMINDER", "Reminder"),
                    ("INCIDENT_CREATED", "Incident Created"),
                    ("SLA_BREACHED", "SLA Breached"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("INVOICE_SENT", "Invoice Sent"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
