# Generated by Django 5.2.8 on 2026-07-19 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("customers", "0001_initial"),
        ("incidents", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paystack_access_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack access code for checkout",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paystack_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Paystack transaction reference",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="billing.tax",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["paystack_reference"], name="billing_inv_paystac_d31489_idx"
            ),
        ),
    ]
