# Generated by Django 5.2.8 on 2026-08-10 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_invoice_materials_total_purchaseditem"),
        ("customers", "0001_initial"),
        ("incidents", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "ordering": ["created_at"],
                "verbose_name_plural": "Invoice Items",
            },
        ),
        migrations.AlterModelOptions(
            name="invoicesequence",
            options={"ordering": ["prefix", "year"]},
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceapproval",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceitemtax",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="invoicesequence",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transport_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost of transportation/delivery for this invoice.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="late_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="materials_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total cost of materials purchased for the customer.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paystack_access_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack access code for checkout.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paystack_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Paystack transaction reference.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="line_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemtax",
            name="rate_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoicesequence",
            name="prefix",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="billing.ledgeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="recurringinvoice",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_invoices",
                to="billing.invoicetemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["transport_cost"], name="billing_inv_transpo_3b8ce0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("base_currency", "target_currency", "effective_date"),
                name="unique_exchange_rate_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("transport_cost__gte", 0)),
                name="invoice_transport_cost_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceapproval",
            constraint=models.UniqueConstraint(
                fields=("invoice", "level"), name="unique_invoice_approval_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitemtax",
            constraint=models.UniqueConstraint(
                fields=("item", "tax"), name="unique_invoice_item_tax"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicesequence",
            constraint=models.UniqueConstraint(
                fields=("prefix", "year"), name="unique_invoice_sequence_prefix_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentryline",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit", 0), ("credit", 0), _connector="OR"),
                name="journal_line_not_both_debit_credit",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("refunded_amount__gte", 0)),
                name="payment_refunded_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("refunded_amount__lte", models.F("amount"))),
                name="payment_refund_not_exceed_amount",
            ),
        ),
    ]
