# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Plan name (e.g., 'Pro Artisan')", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per billing cycle",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="GHS", max_length=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Duration in days (e.g., 30 for monthly)"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features included in this plan",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is available for purchase",
                    ),
                ),
                (
                    "trial_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of free trial days (0 = no trial)"
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of users allowed under this plan",
                    ),
                ),
                (
                    "max_listings",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of listings/services allowed",
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this plan includes priority support",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["price"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="subscriptio_is_acti_dd0689_idx"
                    ),
                    models.Index(
                        fields=["billing_cycle"], name="subscriptio_billing_10a8e9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateField(help_text="Date when the subscription starts"),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Date when the subscription ends (if not renewed)"
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the trial ends (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscription was cancelled",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIAL", "Trial"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("PAUSED", "Paused"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the subscription automatically renews",
                    ),
                ),
                (
                    "subscription_reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this subscription",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference from the payment gateway (Paystack/Stripe)",
                        max_length=100,
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full response from the payment gateway",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="subscriptio_user_id_2a19e8_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="subscriptio_end_dat_60694b_idx"
                    ),
                    models.Index(
                        fields=["subscription_reference"],
                        name="subscriptio_subscri_1152e9_idx",
                    ),
                ],
            },
        ),
    ]
