# Generated by Django 5.2.8 on 2026-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_category", "0002_auto_20260719_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentcategory",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated code like CAT-001",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated code like SUB-001",
                max_length=100,
                unique=True,
            ),
        ),
    ]
