# Generated by Django 5.2.8 on 2026-08-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incident_category",
            "0003_alter_incidentcategory_code_alter_subcategory_code",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentcategory",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
