# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=1, help_text="Estimated duration in hours."
                    ),
                ),
                (
                    "minimum_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Typical minimum market price.",
                        max_digits=10,
                    ),
                ),
                (
                    "maximum_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Typical maximum market price.",
                        max_digits=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        related_query_name="service",
                        to="categories.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        related_query_name="service",
                        to="categories.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="services_se_name_32d28c_idx"),
                    models.Index(
                        fields=["category"], name="services_se_categor_7ca2f8_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="services_se_is_acti_91b7ea_idx"
                    ),
                    models.Index(fields=["slug"], name="services_se_slug_4657d0_idx"),
                ],
                "unique_together": {("category", "name")},
            },
        ),
    ]
