# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("incidents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")],
                        db_index=True,
                        default="INBOUND",
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                        ],
                        default="PHONE",
                        max_length=20,
                    ),
                ),
                ("caller_number", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("INCIDENT_CREATED", "Incident Created"),
                            ("INCIDENT_UPDATED", "Incident Updated"),
                            ("INFORMATION_PROVIDED", "Information Provided"),
                            ("FOLLOW_UP_REQUIRED", "Follow-up Required"),
                            ("NO_ACTION", "No Action"),
                        ],
                        db_index=True,
                        default="INCIDENT_CREATED",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="customers.customer",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Log",
                "verbose_name_plural": "Call Logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="call_center_referen_f1e925_idx"
                    ),
                    models.Index(
                        fields=["agent", "started_at"],
                        name="call_center_agent_i_78c7c6_idx",
                    ),
                    models.Index(
                        fields=["customer"], name="call_center_custome_68177b_idx"
                    ),
                    models.Index(
                        fields=["incident"], name="call_center_inciden_9bcba8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="call_center_status_4e84f5_idx"
                    ),
                    models.Index(
                        fields=["direction"], name="call_center_directi_22641c_idx"
                    ),
                    models.Index(
                        fields=["disposition"], name="call_center_disposi_d2a259_idx"
                    ),
                ],
            },
        ),
    ]
