# Generated by Django 5.2.8 on 2026-09-20 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[("psychometric", "Psychometric"), ("skill", "Skill")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("questions", models.JSONField(default=list)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("max_attempts", models.PositiveIntegerField(default=2)),
                ("pass_threshold", models.PositiveSmallIntegerField(default=70)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("category_slug", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        limit_choices_to={"kind": "skill"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skills",
                        to="provider.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("question_order", models.JSONField(default=list)),
                ("answers", models.JSONField(default=dict)),
                ("score", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(default=False)),
                ("timed_out", models.BooleanField(default=False)),
                ("breakdown", models.JSONField(blank=True, default=list)),
                ("is_submitted", models.BooleanField(default=False)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="provider.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "assessment", "-started_at"],
                        name="provider_as_user_id_0cd3ac_idx",
                    )
                ],
                "unique_together": {("user", "assessment", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="ArtisanSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("best_score", models.FloatField(default=0.0)),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artisan_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_artisan_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artisans",
                        to="provider.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-passed_at"],
                "unique_together": {("user", "skill")},
            },
        ),
    ]
