# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="React icon name or CSS icon class.",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="categories__name_e3ad98_idx"),
                    models.Index(fields=["slug"], name="categories__slug_9b1a28_idx"),
                    models.Index(
                        fields=["is_active"], name="categories__is_acti_3ca3e4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        related_query_name="subcategory",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="categories__categor_0b5d56_idx"
                    ),
                    models.Index(fields=["name"], name="categories__name_c6c0c6_idx"),
                    models.Index(
                        fields=["is_active"], name="categories__is_acti_9e35d6_idx"
                    ),
                ],
                "unique_together": {("category", "name")},
            },
        ),
    ]
