# Generated by Django 5.2.8 on 2026-07-24 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
        ('incident_category', '0002_auto_20260719_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary trade area (e.g., Construction, Electrical)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisans', to='incident_category.incidentcategory'),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='legacy_skills',
            field=models.ManyToManyField(blank=True, help_text='Legacy skills (deprecated – use skills field instead)', related_name='artisans_legacy', to='artisans.skill'),
        ),
        migrations.AlterField(
            model_name='artisanavailability',
            name='is_working',
            field=models.BooleanField(default=True, help_text='Whether the artisan works on this day'),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='average_rating',
            field=models.FloatField(default=0.0, help_text='Average rating from completed jobs (0-5)'),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the artisan is currently available for new jobs'),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='max_concurrent_jobs',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum number of jobs the artisan can handle simultaneously'),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Specific skills (subcategories) the artisan possesses', related_name='artisans', to='incident_category.subcategory'),
        ),
    ]
