# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("version", models.CharField(db_index=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("cohere", "Cohere"),
                            ("google", "Google AI"),
                            ("local", "Local Model"),
                            ("custom", "Custom"),
                        ],
                        default="openai",
                        max_length=20,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat / Conversation"),
                            ("embedding", "Embedding"),
                            ("classification", "Classification"),
                            ("recommendation", "Recommendation"),
                            ("matching", "Matching"),
                            ("translation", "Translation"),
                            ("generation", "Generation"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="Provider's model ID (e.g., gpt-4, claude-3)",
                        max_length=100,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Model-specific configuration (temperature, top_p, etc.)",
                    ),
                ),
                ("max_tokens", models.PositiveIntegerField(default=4096)),
                (
                    "cost_per_1k_tokens",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default model for this type"
                    ),
                ),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("total_successful", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-is_active", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "model_type"],
                        name="ai_aimodel_is_acti_c14c3d_idx",
                    ),
                    models.Index(
                        fields=["provider"], name="ai_aimodel_provide_488d96_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="ai_aimodel_is_defa_bd0725_idx"
                    ),
                ],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("request_type", models.CharField(db_index=True, max_length=50)),
                ("input_data", models.JSONField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, null=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("tokens_prompt", models.PositiveIntegerField(default=0)),
                ("tokens_completion", models.PositiveIntegerField(default=0)),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated cost of this request",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="ai.aimodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="ai_aireques_user_id_eed442_idx"
                    ),
                    models.Index(
                        fields=["model", "status"],
                        name="ai_aireques_model_i_60be1a_idx",
                    ),
                    models.Index(
                        fields=["request_type"], name="ai_aireques_request_fe007d_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="ai_aireques_status_c56da2_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="ai_aireques_request_111faf_idx"
                    ),
                ],
            },
        ),
    ]
