# Generated by Django 5.2.8 on 2026-07-18 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncidentPriority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated code like PRI-001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                (
                    "resolution_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "escalation_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("color_code", models.CharField(blank=True, max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Incident Priority",
                "verbose_name_plural": "Incident Priorities",
                "ordering": ["ordering", "name"],
            },
        ),
    ]
