# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Official business registration number",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="companies/"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Company contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Company phone number", max_length=20
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Company website")),
                ("address", models.TextField(blank=True, help_text="Physical address")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the company is currently active",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether the company has been verified"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="companies_c_name_2d8260_idx"),
                    models.Index(fields=["slug"], name="companies_c_slug_45751b_idx"),
                    models.Index(
                        fields=["is_active"], name="companies_c_is_acti_03043b_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="companies_c_is_veri_542ff2_idx"
                    ),
                ],
            },
        ),
    ]
