# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        help_text="The actual file",
                        max_length=500,
                        upload_to="uploads/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, help_text="Original filename", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="Size in bytes"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="Detected file type (image, video, document, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AVATAR", "Avatar"),
                            ("PORTFOLIO", "Portfolio"),
                            ("SERVICE", "Service"),
                            ("CHAT", "Chat Attachment"),
                            ("DOCUMENT", "Document"),
                            ("REPORT", "Report"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated thumbnail",
                        null=True,
                        upload_to="thumbnails/%Y/%m/%d/",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the file is publicly accessible",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, file will be deleted after this date",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional reference to the object this file is attached to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Media Files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "category"],
                        name="media_media_user_id_c841a7_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="media_media_content_43cba4_idx",
                    ),
                    models.Index(
                        fields=["file_type"], name="media_media_file_ty_218bcf_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="media_media_is_acti_8958d6_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="media_media_created_74471a_idx"
                    ),
                ],
            },
        ),
    ]
