# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("incident_category", "0001_initial"),
        ("incidents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        help_text="If set, applies only to this priority",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("response_hours", models.PositiveIntegerField(default=1)),
                ("resolution_hours", models.PositiveIntegerField(default=24)),
                (
                    "escalation_after_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("business_hours_only", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, applies only to this category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="incident_category.incidentcategory",
                    ),
                ),
                (
                    "escalation_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sla_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Policy",
                "verbose_name_plural": "SLA Policies",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="SLATracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_response", models.DateTimeField()),
                ("target_resolution", models.DateTimeField()),
                ("target_escalation", models.DateTimeField(blank=True, null=True)),
                ("response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_TRACK", "On Track"),
                            ("AT_RISK", "At Risk"),
                            ("BREACHED", "Breached"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="ON_TRACK",
                        max_length=20,
                    ),
                ),
                ("breach_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sla_escalated_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_tracker",
                        to="incidents.incident",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sla.slapolicy"
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Tracker",
                "verbose_name_plural": "SLA Trackers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident"], name="sla_slatrac_inciden_b2b07f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="sla_slatrac_status_da9554_idx"
                    ),
                    models.Index(
                        fields=["target_resolution"],
                        name="sla_slatrac_target__26de40_idx",
                    ),
                    models.Index(
                        fields=["target_escalation"],
                        name="sla_slatrac_target__4bfab8_idx",
                    ),
                ],
            },
        ),
    ]
