# Generated by Django 5.2.8 on 2026-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the setting (e.g., 'site_name')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="The value of the setting (stored as string, parsed according to data_type)"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("FLOAT", "Float"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON"),
                            ("LIST", "List"),
                            ("EMAIL", "Email"),
                            ("URL", "URL"),
                        ],
                        default="STRING",
                        help_text="Data type for parsing the value",
                        max_length=10,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("PAYMENT", "Payment"),
                            ("EMAIL", "Email"),
                            ("NOTIFICATION", "Notification"),
                            ("SECURITY", "Security"),
                            ("FEATURES", "Features"),
                            ("INTEGRATION", "Integration"),
                            ("SEO", "SEO"),
                            ("SOCIAL", "Social"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        help_text="Group for organising settings",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Purpose of this setting"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this setting is exposed to the public API",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this setting can be edited via the admin",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this setting must have a value",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional options (e.g., {'min': 0, 'max': 100, 'choices': [...]})",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "App Settings",
                "ordering": ["group", "key"],
                "indexes": [
                    models.Index(fields=["group"], name="app_setting_group_639cfa_idx"),
                    models.Index(fields=["key"], name="app_setting_key_6c42fd_idx"),
                    models.Index(
                        fields=["is_public"], name="app_setting_is_publ_01d8c3_idx"
                    ),
                ],
            },
        ),
    ]
