# Generated by Django 5.2.8 on 2026-07-21 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the audit log entry', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete'), ('RESTORE', 'Restore'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('PRINT', 'Print'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('ARCHIVE', 'Archive'), ('UNARCHIVE', 'Unarchive'), ('MERGE', 'Merge'), ('SPLIT', 'Split'), ('VERIFY', 'Verify'), ('UNVERIFY', 'Unverify'), ('ASSIGN', 'Assign'), ('REASSIGN', 'Reassign'), ('ESCALATE', 'Escalate'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('COMPLETE', 'Complete')], db_comment='Type of action performed', db_index=True, help_text='The action performed by the user', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_comment='How critical this action is', default='LOW', help_text='How critical this action is', max_length=10)),
                ('module', models.CharField(blank=True, db_comment="App/module name (e.g., 'incidents')", db_index=True, help_text="App/module name (e.g., 'incidents')", max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='Primary key of the logged object', max_length=255)),
                ('object_repr', models.CharField(blank=True, db_comment='String representation of the object', help_text='String representation of the object', max_length=500)),
                ('old_values', models.JSONField(blank=True, db_comment='Previous values (before action)', help_text='Previous values (before action)', null=True)),
                ('new_values', models.JSONField(blank=True, db_comment='New values (after action)', help_text='New values (after action)', null=True)),
                ('success', models.BooleanField(db_comment='Whether the operation succeeded', db_index=True, default=True, help_text='Whether the operation succeeded')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, db_comment='HTTP status code', help_text='HTTP status code', null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, db_comment='Execution time in milliseconds', help_text='Execution time in milliseconds', null=True)),
                ('request_id', models.CharField(blank=True, db_comment='Unique ID of the request', db_index=True, help_text='Unique ID of the request', max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_comment='ID linking multiple requests in a workflow', db_index=True, help_text='ID linking multiple requests in a workflow', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_comment='Client IP (with proxy support)', help_text='Client IP (with proxy support)', null=True)),
                ('path', models.CharField(blank=True, db_comment='Request path', help_text='Request path', max_length=255)),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], db_comment='HTTP method', help_text='HTTP method', max_length=10)),
                ('user_agent', models.TextField(blank=True, help_text='Raw user agent string')),
                ('browser', models.CharField(blank=True, db_comment='Browser family (parsed)', help_text='Browser family (parsed)', max_length=50)),
                ('operating_system', models.CharField(blank=True, db_comment='OS family (parsed)', help_text='OS family (parsed)', max_length=50)),
                ('device', models.CharField(blank=True, db_comment='Device family (parsed)', help_text='Device family (parsed)', max_length=50)),
                ('description', models.TextField(blank=True, db_comment='Human‑readable description of the event', help_text='Human‑readable description of the event')),
                ('exception', models.TextField(blank=True, db_comment='Exception traceback (if any)', help_text='Exception traceback (if any)')),
                ('archived', models.BooleanField(db_comment='Whether this log entry has been archived', db_index=True, default=False, help_text='Whether this log entry has been archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the log entry was created')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the logged object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(blank=True, db_comment='For multi‑tenant support', help_text='For multi‑tenant support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(db_comment='User who performed the action', help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'), models.Index(fields=['module', 'created_at'], name='audit_logs_module_cb850a_idx'), models.Index(fields=['action', 'module'], name='audit_logs_action_559e21_idx'), models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx'), models.Index(fields=['correlation_id'], name='audit_logs_correla_953e51_idx'), models.Index(fields=['organization'], name='audit_logs_organiz_b941b8_idx'), models.Index(fields=['severity', 'created_at'], name='audit_logs_severit_00ae5a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_ms__isnull', True), ('duration_ms__gte', 0), _connector='OR'), name='audit_duration_positive'), models.CheckConstraint(condition=models.Q(('response_status__isnull', True), models.Q(('response_status__gte', 100), ('response_status__lte', 599)), _connector='OR'), name='audit_http_status_valid')],
            },
        ),
    ]
