# Generated by Django 5.2.8 on 2026-07-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_comment='ID linking multiple requests in a workflow', db_index=True, help_text='ID linking multiple requests in a workflow', max_length=100, null=True),
        ),
    ]
