# Generated by Django 5.2.8 on 2026-07-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current available balance",
                        max_digits=12,
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount credited (all time)",
                        max_digits=12,
                    ),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount debited (all time)",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS",
                        help_text="Wallet currency (e.g., GHS, USD)",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the wallet is active"
                    ),
                ),
                (
                    "last_transaction_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last transaction",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wallets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wallet balance after this transaction",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the transaction was processed (if completed)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (e.g., related booking, payment ref)",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wallet Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["user", "is_active"], name="wallets_wal_user_id_a261b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "transaction_type"],
                name="wallets_wal_wallet__cb1d14_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["reference"], name="wallets_wal_referen_41fe73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["status"], name="wallets_wal_status_3d8d99_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["created_at"], name="wallets_wal_created_8018ab_idx"
            ),
        ),
    ]
